name: Release

on:
  push:
    tags:
      - 'v*'

      
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write       # To publish a GitHub release & commit version updates
      issues: write         # To comment on released issues
      pull-requests: write  # To comment on released pull requests
      id-token: write       # If needed for OIDC authentication (e.g., with external registries)
      packages: write       # To publish to GitHub Packages
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: 'https://npm.pkg.github.com'
          scope: "@${{ github.repository_owner }}"

      - run: pnpm install
      
      - name: Build
        run: pnpm build

      - name: Publish a new release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release